# yaml-language-server: $schema=https://raw.githubusercontent.com/RedHatInsights/frontend-components/refs/heads/master/packages/config-utils/src/feo/spec/frontend-crd.schema.json
apiVersion: v1
kind: Template
metadata:
  name: learning-resources
objects:
  - apiVersion: cloud.redhat.com/v1alpha1
    kind: Frontend
    metadata:
      name: learning-resources
    spec:
      envName: ${ENV_NAME}
      title: Learning resources
      deploymentRepo: https://github.com/RedHatInsights/learning-resources
      API:
        versions:
          - v1
      frontend:
        paths:
          - /apps/learning-resources
      image: ${IMAGE}:${IMAGE_TAG}
      feoConfigEnabled: true
      bundleSegments:
        - segmentId: learning-resources-openshift
          bundleId: openshift
          position: 10000
          navItems:
            - id: learningResourcesOpenShift
              title: Learning Resources
              href: /openshift/learning-resources
        - segmentId: learning-resources-ansible
          bundleId: ansible
          position: 10000
          navItems:
            - id: learningResourcesAnsible
              title: Learning Resources
              href: /ansible/learning-resources
        - segmentId: learning-resources-insights
          bundleId: insights
          position: 10000
          navItems:
            - id: learningResourcesInsights
              title: Learning Resources
              href: /insights/learning-resources
        - segmentId: learning-resources-edge
          bundleId: edge
          position: 10000
          navItems:
            - id: learningResourcesEdge
              title: Learning Resources
              href: /edge/learning-resources
        - segmentId: learning-resources-iam
          bundleId: iam
          position: 10000
          navItems:
            - id: learningResourcesIAM
              title: Learning Resources
              href: /iam/learning-resources
        - segmentId: learning-resources-settings
          bundleId: settings
          position: 10000
          navItems:
            - id: learningResourcesSettings
              title: Learning Resources
              href: /settings/learning-resources
      module:
        manifestLocation: /apps/learning-resources/fed-mods.json
        modules:
          - id: learningResources
            module: ./RootApp
            routes:
              - pathname: "/openshift/learning-resources"
                props:
                  bundle: openshift
              - pathname: "/ansible/learning-resources"
                props:
                  bundle: ansible
              - pathname: "/insights/learning-resources"
                props:
                  bundle: insights
              - pathname: "/edge/learning-resources"
                props:
                  bundle: edge
              - pathname: "/settings/learning-resources"
                props:
                  bundle: settings
              - pathname: "/iam/learning-resources"
                props:
                  bundle: iam
          - id: globalLearningResourcesPage
            module: ./GlobalLearningResourcesPage
            routes:
              - pathname: /learning-resources
          - id: learningResourcesCreator
            module: "./Creator"
            routes:
            - pathname: "/learning-resources/creator"
              exact: true
              permissions:
              - method: featureFlag
                args:
                - platform.chrome.quickstarts.creator
                - true
      searchEntries:
        - id: learning-resources
          title: All Learning Resources
          href: /learning-resources
          description: Access product documentation, tutorials, and other learning materials to support your Red Hat product use.
          alt_title:
            - Learning Resources
parameters:
  - name: ENV_NAME
    required: true
  - name: IMAGE_TAG
    required: true
  - name: IMAGE
    value: quay.io/redhat-services-prod/hcc-platex-services/learning-resources
