apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://github.com/RedHatInsights/learning-resources?rev={{revision}}
    build.appstudio.redhat.com/commit_sha: '{{revision}}'
    build.appstudio.redhat.com/pull_request_number: '{{pull_request_number}}'
    build.appstudio.redhat.com/target_branch: '{{target_branch}}'
    pipelinesascode.tekton.dev/max-keep-runs: "3"
    pipelinesascode.tekton.dev/on-cel-expression: event == "pull_request" && target_branch
      == "master"
    pipelinesascode.tekton.dev/pipeline: https://github.com/catastrophe-brandon/konflux-pipelines/raw/btweed/platform-ui-e2e/pipelines/platform-ui/docker-build-run-all-tests.yaml
  creationTimestamp: null
  labels:
    appstudio.openshift.io/application: learning-resources
    appstudio.openshift.io/component: learning-resources
    pipelines.appstudio.openshift.io/type: build
  name: learning-resources-on-pull-request
  namespace: hcc-platex-services-tenant
spec:
  params:
  - name: git-url
    value: '{{source_url}}'
  - name: revision
    value: '{{revision}}'
  - name: output-image
    value: quay.io/redhat-user-workloads/hcc-platex-services-tenant/learning-resources/learning-resources:on-pr-{{revision}}
  - name: image-expires-after
    value: 5d
  - name: dockerfile
    value: build-tools/Dockerfile
  - name: path-context
    value: .
  - name: rebuild
    value: "true"
  - name: unit-tests-script
    value: |
      #!/bin/bash
      set -ex
      exit 0 
      npm install
      npm run lint
      npm test --  --runInBand --no-cache
  - name: e2e-tests-script
    value: |
      #!/bin/bash
      set -ex
      getent hosts stage.foo.redhat.com
      timeout 120s bash -c 'until curl -k https://stage.foo.redhat.com:1337 > /dev/null 2>&1; do
        echo "Waiting for dev server to be ready"
        sleep 5
      done'
      echo "Dev server ready!"
      echo "HTTP_PROXY is ${HTTP_PROXY}"
      echo "HTTPS_PROXY is ${HTTPS_PROXY}"
      # sleep 2000
      echo "Removing existing node_modules and lock files..."
      rm -rf node_modules package-lock.json
      echo "Installing dependencies..."
      npm install --legacy-peer-deps --prefer-offline --no-audit --no-fund
      npx playwright test      
  - name: proxy-routes-json
    value: |
      @root path /
      handle @root {
          reverse_proxy 127.0.0.1:9912
      }

      handle /index.html {
          reverse_proxy 127.0.0.1:9912
      }

      handle /apps/chrome* {
          reverse_proxy 127.0.0.1:9912
      }

      handle /apps/learning-resources* {
          reverse_proxy 127.0.0.1:8000
      }

      handle /settings/learning-resources* {
          reverse_proxy 127.0.0.1:9912
      }

      handle /openshift/learning-resources* {
          reverse_proxy 127.0.0.1:9912
      }

      handle /ansible/learning-resources* {
          reverse_proxy 127.0.0.1:9912
      }

      handle /insights/learning-resources* {
          reverse_proxy 127.0.0.1:9912
      }

      handle /edge/learning-resources* {
          reverse_proxy 127.0.0.1:9912
      }

      handle /iam/learning-resources* {
          reverse_proxy 127.0.0.1:9912
      }

      handle /learning-resources* {
          reverse_proxy 127.0.0.1:9912
      }
  pipelineRef:
    resolver: git
    params:
    - name: url
      value: https://github.com/catastrophe-brandon/konflux-pipelines
    - name: revision
      value: btweed/platform-ui-e2e
    - name: pathInRepo
      value: pipelines/platform-ui/docker-build-run-all-tests.yaml
  taskRunTemplate:
    serviceAccountName: build-pipeline-learning-resources
  taskRunSpecs:
    - pipelineTaskName: run-e2e-tests
      serviceAccountName: build-pipeline-learning-resources
      podTemplate:
        # Override /etc/hosts to redirect stage.foo.redhat.com to localhost
        hostAliases:
          - ip: "::1"
            hostnames:
              - "stage.foo.redhat.com"
          - ip: "127.0.0.1"
            hostnames:
              - "stage.foo.redhat.com"
  workspaces:
  - name: workspace
    volumeClaimTemplate:
      metadata:
        creationTimestamp: null
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
      status: {}
  - name: git-auth
    secret:
      secretName: '{{ git_auth_secret }}'
status: {}
